language: node_js
node_js:
  - "12.0.0"
sudo: required
services:
    - docker
    
before_install:
  - docker build -t kanishkaw/frontend -f Dockerfile.dev .

script:
  - docker run kanishkaw/frontend npm run test -- --coverage